### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [makamys/SmartMoving#4] opened 2022-11-28 05:14 UTC
Is this the smart moving mod from this link? 

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1274224-smart-moving

**Comment by tyrael93** [comment] 2022-11-28 08:50
Technically it's a fork of the original smart moving mod you provided the link to. It has a bunch of extra bugfixes and changes.

**Comment by makamys** [comment] 2022-11-28 11:18
Yeah, it's a fork based on Smart Moving 15.6.

**Comment by Fireworkstars46** [comment] 2022-11-29 08:13
Also is there a discord server for the mod or no?

**Comment by makamys** [comment] 2022-11-29 16:24
Not officially, I hang around in Et Futurum Requiem's discord though.

**Comment by Fireworkstars46** [comment] 2022-12-01 09:51
Do I ask here or there?

**Comment by makamys** [comment] 2022-12-01 16:24
Here is fine.

**Comment by Fireworkstars46** [comment] 2022-12-02 06:07
Ok. So for my main question is I want to use the smart moving mod for 1.6.4 and I have it but for some reason I can't use smart moving's sprint keybind key for vanilla MC sprint speed. Is it not possible or is the sprint key only work with the genetic smart moving sprinting?

**Comment by makamys** [comment] 2022-12-02 16:39
In the original version of Smart Moving, the sprint key activates Smart Moving's sprint. To perform the vanilla sprint, you have to double tap W.

This is something I fixed in my fork, by making it so releasing the sprint key transitions you to the vanilla sprint rather than walking. I don't intend to support versions other than 1.7.10 however, so you're out of luck there.

**Comment by Fireworkstars46** [comment] 2022-12-03 05:17
So there's no way to use the vanilla sprint with the smart moving sprint key?

**Comment by makamys** [comment] 2022-12-03 20:16
As far as I know, no.

**Comment by Fireworkstars46** [comment] 2022-12-04 03:54
Would me using the smart movings sprint but changing the speed settings work?

**Comment by makamys** [comment] 2022-12-04 16:38
I think it would, the issue is releasing the sprint key would still terminate the sprint. The vanilla sprint speed multiplier is 1.3 FYI.

**Closed** 2023-05-08 15:48 UTC
